export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#f0f7ff',
                    100: '#e0f0fe',
                    200: '#bae6fd',
                    300: '#7dd3fc',
                    400: '#38bdf8',
                    500: '#0ea5e9',
                    600: '#0284c7',
                    700: '#0369a1',
                    800: '#075985',
                    900: '#0c3d66',
                },
                secondary: {
                    50: '#f7f2ff',
                    100: '#f0e8ff',
                    200: '#e9d5ff',
                    300: '#ddb2ff',
                    400: '#d084ff',
                    500: '#c15bff',
                    600: '#a637ff',
                    700: '#8b1aff',
                    800: '#7000ff',
                    900: '#6600cc',
                },
                accent: {
                    50: '#fef8f0',
                    100: '#fdf0e0',
                    200: '#fbe0c1',
                    300: '#f8c9a0',
                    400: '#f5a962',
                    500: '#f17d3c',
                    600: '#e55a2a',
                    700: '#d63d22',
                    800: '#b82a1d',
                    900: '#8a1f18',
                },
            },
            fontFamily: {
                sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', '"Helvetica Neue"', 'Arial', 'sans-serif'],
                display: ['Poppins', 'system-ui', 'sans-serif'],
                mono: ['Fira Code', 'monospace'],
            },
            fontSize: {
                xs: ['0.75rem', { lineHeight: '1rem' }],
                sm: ['0.875rem', { lineHeight: '1.25rem' }],
                base: ['1rem', { lineHeight: '1.5rem' }],
                lg: ['1.125rem', { lineHeight: '1.75rem' }],
                xl: ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideIn: {
                    '0%': { transform: 'translateX(100%)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-10px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.95)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-1000px 0' },
                    '100%': { backgroundPosition: '1000px 0' },
                },
            },
            animation: {
                fadeIn: 'fadeIn 0.3s ease-in',
                slideIn: 'slideIn 0.3s ease-in-out',
                slideDown: 'slideDown 0.3s ease-out',
                scaleIn: 'scaleIn 0.2s ease-out',
                shimmer: 'shimmer 2s infinite',
            },
            boxShadow: {
                sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
                base: '0 2px 4px 0 rgb(0 0 0 / 0.08)',
                md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                lg: '0 10px 15px -3px rgb(0 0 0 / 0.12)',
                xl: '0 20px 25px -5px rgb(0 0 0 / 0.15)',
                '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.15)',
                inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
            },
            spacing: {
                '4.5': '1.125rem',
                '5.5': '1.375rem',
                '7.5': '1.875rem',
                '8.5': '2.125rem',
            },
        },
    },
    plugins: [],
}
